[package]
name = "git-hooks"
version = "1.0.0"
authors = ["fr3dch3n <git@frederik-mars.de>"]
edition = "2018"

[dependencies]
regex = "1.3.1"
exitcode = "1.1.2"
yaml-rust = "0.4"

[[bin]]
name = "commit-msg"
path = "src/commit_msg/main.rs"
